name: ToggleDeathCoordinates
version: '1.0'
main: toggleDeathCoordinates.ToggleDeathCoordinates
api-version: 1.19
description: Displays the death coordinates of players to them upon death.

commands:
  tdc:
    description: Turn the display of your death coordinates in chat on or off.
    aliases: [toggledeathcoordinates]
    
permissions:
  tdc.use:
    description: Permission to toggle your death coordinates.
    default: op